package segundoParcial;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class AlumnoDialog extends javax.swing.JDialog {

    private ModalResult modalResult;
    private ArrayList<Alumno> alumnos;

   public AlumnoDialog(java.awt.Frame parent, boolean modal){
       super(parent,modal);
       initComponents();
     
   }
   
   private double validarCalificacion()throws CalificacionException{
       double cal = -1;
       
       try{
           cal = Double.valueOf(edtCalificacion.getText());
           if((cal<0.0)|| (cal>10.0)){
               
               throw new CalificacionException();
           }
           return cal;
       }catch(Exception e){
           
           throw new CalificacionException("Hubo un error en la calificación");
       } 
   }
   
    private String validarNombre() throws NombreException{
        if("".equals(edtNombre.getText())){
            throw new NombreException("¡Nombre Vacio!");            
        }   
        return "si";          
       }
    
     private String validarPaterno() throws PaternoException{
        if("".equals(edtPaterno.getText())){
            throw new PaternoException("¡Apellido Paterno vacio!");            
        }   
        return "si";          
       }
      private String validarMaterno() throws MaternoException{
        if("".equals(edtMaterno.getText())){
            throw new MaternoException("¡Apellido materno vacio!");            
        }   
        return "si";          
       }
      

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNombre = new javax.swing.JTextField();
        edtPaterno = new javax.swing.JTextField();
        edtMaterno = new javax.swing.JTextField();
        edtCalificacion = new javax.swing.JTextField();
        cmbCarrera = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 16))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("A paterno:");

        jLabel3.setText("A materno:");

        jLabel4.setText("Carerra:");

        jLabel5.setText("Calificación:");

        cmbCarrera.setModel(new DefaultComboBoxModel(Carreras.values()));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtMaterno)
                    .addComponent(edtPaterno)
                    .addComponent(edtNombre)
                    .addComponent(edtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        modalResult = ModalResult.mrCancelar;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       try{
            String nombre = validarNombre();
            String paterno = validarPaterno();
            String materno = validarMaterno();
            double cal  = validarCalificacion();
                    
            
            
                Alumno alumno = new Alumno(
                edtNombre.getText(),
                edtPaterno.getText(),
                edtMaterno.getText(),
                Double.valueOf(edtCalificacion.getText()),
                (Carreras)cmbCarrera.getSelectedItem()
        );
        modalResult = ModalResult.mrAceptar;
       this.setVisible(false);
       }catch(CalificacionException e){
           JOptionPane.showMessageDialog(this, e.getMessage(),"¡Error!", JOptionPane.ERROR_MESSAGE);
           edtCalificacion.requestFocus();
       }catch(PaternoException e){
           JOptionPane.showMessageDialog(this, e.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
           edtPaterno.requestFocus();;
       } catch(MaternoException e){
           JOptionPane.showMessageDialog(this, e.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
           edtMaterno.requestFocus();
       } catch(NombreException e){
           JOptionPane.showMessageDialog(this, e.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
           edtNombre.requestFocus();
       }
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public ModalResult mostrarDialogo(){
        modalResult = ModalResult.mrCancelar;
        edtNombre.setText("");
        edtPaterno.setText("");
        edtMaterno.setText("");
        edtCalificacion.setText("");
        cmbCarrera.setSelectedIndex(0);
        this.setVisible(true);
        return modalResult;
    }
    
    
    
    public ModalResult mostrarAlumno(ArrayList<Alumno> alumnos, int n){
         modalResult = ModalResult.mrCancelar;
        edtNombre.requestFocus();
        edtNombre.setText(alumnos.get(n).getNombre());
        edtPaterno.setText(alumnos.get(n).getPaterno());
        edtMaterno.setText(alumnos.get(n).getMaterno());
        edtCalificacion.setText(alumnos.get(n).getCalificacion().toString());
        cmbCarrera.setSelectedIndex(0);
        this.setVisible(true);
        return modalResult;

        
    }
    
    public Alumno getAlumno(){
        Alumno alumno = new Alumno(
                edtNombre.getText(),
                edtPaterno.getText(),
                edtMaterno.getText(),
                Double.valueOf(edtCalificacion.getText()),
                (Carreras)cmbCarrera.getSelectedItem()
        );
        
        return alumno;
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlumnoDialog dialog = new AlumnoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JTextField edtCalificacion;
    private javax.swing.JTextField edtMaterno;
    private javax.swing.JTextField edtNombre;
    private javax.swing.JTextField edtPaterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
