/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundoParcial;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.tools.ShellFunctions.input;

/**
 *
 * @author alave
 */
public class PrincipalFrame extends javax.swing.JFrame {

   private AlumnosModel alumnosModel;
   private ArrayList <Alumno> alumnos; 
   private AlumnoDialog dlgAlumno;
   
   
   public PrincipalFrame() {
      
       cargarAlumnos();
       alumnosModel = new AlumnosModel(alumnos);
       initComponents();
       dlgAlumno = new AlumnoDialog(this, true); 
        this.setExtendedState(MAXIMIZED_BOTH);   
        
        
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNuevoA = new javax.swing.JMenuItem();
        menuModi = new javax.swing.JMenuItem();
        menuElim = new javax.swing.JMenuItem();
        menuGuar = new javax.swing.JMenuItem();
        btnAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAlumnos.setModel(alumnosModel);
        tblAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblAlumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 502));

        btnSalir.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, -1, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jMenu1.setText("Alumno");

        menuNuevoA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNuevoA.setText("Nuevo alumno");
        menuNuevoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoAActionPerformed(evt);
            }
        });
        jMenu1.add(menuNuevoA);

        menuModi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuModi.setText("Modificar alumno");
        menuModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModiActionPerformed(evt);
            }
        });
        jMenu1.add(menuModi);

        menuElim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuElim.setText("Eliminar alumno");
        menuElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElimActionPerformed(evt);
            }
        });
        jMenu1.add(menuElim);

        menuGuar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuGuar.setText("Guardar");
        menuGuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuar);

        jMenuBar1.add(jMenu1);

        btnAyuda.setText("Ayuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Informacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnAyuda.add(jMenuItem1);

        jMenuBar1.add(btnAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNuevoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoAActionPerformed
           ModalResult mr = dlgAlumno.mostrarDialogo();
   
   if(mr == ModalResult.mrAceptar){
       
       Alumno alumno = dlgAlumno.getAlumno();
   
      alumnos.add(alumno);
      alumnosModel.fireTableDataChanged();
   }
    }//GEN-LAST:event_menuNuevoAActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModiActionPerformed
        int n = tblAlumnos.getSelectedRow();
        if(n<0){
            JOptionPane.showMessageDialog(this,"No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            
            ModalResult mr = dlgAlumno.mostrarAlumno(alumnos, n);
            
            if(mr == ModalResult.mrAceptar){
                
                Alumno alumno = dlgAlumno.getAlumno();
                alumnos.set(n, alumno);
                alumnosModel.fireTableDataChanged();
             }
         
        }
    }//GEN-LAST:event_menuModiActionPerformed

    private void menuElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElimActionPerformed
        
        
        
        int numero = tblAlumnos.getSelectedRow();
        
        int r2 = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas elimnarlo?", "Eliminar", JOptionPane.YES_NO_OPTION);
        System.out.println(r2);
        
        if(r2 == JOptionPane.YES_OPTION){
            alumnos.remove(numero);
            alumnosModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_menuElimActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       InformacionDialog informacionDialog = new InformacionDialog(this,true);
       informacionDialog.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuGuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuarActionPerformed
       try{
            File file = new File("alumnos.dat");
            FileOutputStream output = new FileOutputStream(file);
            ObjectOutputStream writer = new ObjectOutputStream(output);
            
            writer.writeObject(alumnos);
            
            writer.close();
            output.close();
            
       }catch (IOException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_menuGuarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
       
        try{
            
            File file = new File("alumnos.dat");
        FileInputStream input = new FileInputStream(file);
        ObjectInputStream reader = new ObjectInputStream(input);
        
        alumnos = (ArrayList<Alumno>)reader.readObject();
        
        reader.close();
        input.close();
        
        } catch (IOException e) {
          
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
       }
        
        
  
       for(int i = 0; i<alumnos.size(); i++){
        
        Alumno tmp = alumnos.get(i);
           System.out.println(tmp.getNombre());
                 
         } 
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cargarAlumnos(){
        File file = new File("alumnos.dat");
        if(file.exists()){
        try{
            
            
            FileInputStream input = new FileInputStream(file);
            ObjectInputStream reader = new ObjectInputStream(input);
                    alumnos = (ArrayList<Alumno>)reader.readObject();
                    
                    reader.close();
                    input.close();
        }catch(IOException e){
            
        }catch(ClassNotFoundException ex){
            
        }
        }
        else{
            alumnos = new ArrayList<>();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAyuda;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuElim;
    private javax.swing.JMenuItem menuGuar;
    private javax.swing.JMenuItem menuModi;
    private javax.swing.JMenuItem menuNuevoA;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
